name: Docker
on: [push, pull_request]
jobs:
  Ubuntu:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: 'recursive'
    - name: Set PATH
      run: echo "${HOME}/.local/bin" >> $GITHUB_PATH
    - name: Update apt
      run: sudo apt update
    - name: Install pip dependencies
      run: |
        sudo apt install python3-setuptools python3-wheel
        pip3 install -r requirements.txt
    - name: Install apt dependencies
      run: sudo apt install -y $(bindep -b | tr '\n' ' ')
    - name: Install Boost
      run: |
        wget https://boostorg.jfrog.io/artifactory/main/release/1.80.0/source/boost_1_80_0.tar.gz
        tar -xf boost_1_80_0.tar.gz
        cd boost_1_80_0
        ./bootstrap.sh --with-python=python3 --prefix=/opt/boost
        ./b2 -j 2 --with-python --with-graph --with-iostreams install
    - name: Bootstrap
      run: ./bootstrap.sh
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake ../ -DBOOST_ROOT=/opt/boost -DBUILD_POST_MOD=off
    - name: Make archive
      run: cd build && make dist
    - name: Build
      run: docker build -t jakobandersen/mod:ubuntu-test -f docker/Ubuntu.Dockerfile --build-arg j=2 .
  Fedora:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: 'recursive'
    - name: Set PATH
      run: echo "${HOME}/.local/bin" >> $GITHUB_PATH
    - name: Update apt
      run: sudo apt update
    - name: Install pip dependencies
      run: |
        sudo apt install python3-setuptools python3-wheel
        pip3 install -r requirements.txt
    - name: Install apt dependencies
      run: sudo apt install -y $(bindep -b | tr '\n' ' ')
    - name: Install Boost
      run: |
        wget https://boostorg.jfrog.io/artifactory/main/release/1.80.0/source/boost_1_80_0.tar.gz
        tar -xf boost_1_80_0.tar.gz
        cd boost_1_80_0
        ./bootstrap.sh --with-python=python3 --prefix=/opt/boost
        ./b2 -j 2 --with-python --with-graph --with-iostreams install
    - name: Bootstrap
      run: ./bootstrap.sh
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake ../ -DBOOST_ROOT=/opt/boost -DBUILD_POST_MOD=off
    - name: Make archive
      run: cd build && make dist
    - name: Build
      run: docker build -t jakobandersen/mod:fedora-test -f docker/Fedora.Dockerfile --build-arg j=2 .
  Arch:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: 'recursive'
    - name: Set PATH
      run: echo "${HOME}/.local/bin" >> $GITHUB_PATH
    - name: Update apt
      run: sudo apt update
    - name: Install pip dependencies
      run: |
        sudo apt install python3-setuptools python3-wheel
        pip3 install -r requirements.txt
    - name: Install apt dependencies
      run: sudo apt install -y $(bindep -b | tr '\n' ' ')
    - name: Install Boost
      run: |
        wget https://boostorg.jfrog.io/artifactory/main/release/1.80.0/source/boost_1_80_0.tar.gz
        tar -xf boost_1_80_0.tar.gz
        cd boost_1_80_0
        ./bootstrap.sh --with-python=python3 --prefix=/opt/boost
        ./b2 -j 2 --with-python --with-graph --with-iostreams install
    - name: Bootstrap
      run: ./bootstrap.sh
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake ../ -DBOOST_ROOT=/opt/boost -DBUILD_POST_MOD=off
    - name: Make archive
      run: cd build && make dist
    - name: Build
      run: docker build -t jakobandersen/mod:arch-test -f docker/Arch.Dockerfile --build-arg j=2 .
